### ISSUE TITLE
Misc Updates

### ISSUE THREAD

**Issue by eberger727** [hyperledger/firefly-sandbox#59]
- [x] Refactor Transaction Map (#75)
- [x] Info icon popovers for each field (#73)
- [x] Search params to hold state across refreshes (#62)
- [x] Formatting text size and loading states (#70)
